version: "3.3"

services:
  react-elliotjreed:
    image: elliotjreed/www.elliotjreed.com:latest
    container_name: react-elliotjreed
    restart: always
    networks:
      - elliotjreed
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.elliotjreed.com"
      - "traefik.protocol=http"
      - "traefik.port=81"

networks:
  elliotjreed:
  web:
    external: true
