version: "3.6"

services:
  react-elliotjreed:
    image: elliotjreed/www.elliotjreed.com:latest
    container_name: react-elliotjreed
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.www.frontend.rule=Host:www.elliotjreed.com"
      - "traefik.nonwww.frontend.rule=Host:elliotjreed.com"
      - "traefik.protocol=h2c"
      - "traefik.port=81"

networks:
  web:
    external: true
