version: "3.6"

services:
  react-elliotjreed:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: react-elliotjreed
    restart: always
    volumes:
      - ./dist:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - elliotjreed
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.elliotjreed.com"
      - "traefik.protocol=https"
      - "traefik.port=81"

networks:
  elliotjreed:
    name: elliotjreed
