name: CI
on: [push, pull_request]
jobs:
  ci:
    name: Runs Javascript tests and build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install, build, and test
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn install
      - run: yarn lint
      - run: yarn coverage
      - run: yarn build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag
        id: docker_tag
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ ${BRANCH} = "master" ]; then TAG=$(date +%Y%m%d%H%M%S);BUILD=latest; else TAG=${BRANCH//[^a-zA-Z0-9]/-};BUILD=staging; fi;
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=build::${BUILD}

      - name: Build Docker image and push to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            elliotjreed/www.elliotjreed.com:${{ steps.docker_tag.outputs.tag }}
            elliotjreed/www.elliotjreed.com:${{ steps.docker_tag.outputs.build }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
